# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wrewards_parser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 350)
        MainWindow.setMinimumSize(QtCore.QSize(850, 350))
        MainWindow.setMaximumSize(QtCore.QSize(850, 350))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro")
        font.setPointSize(20)
        font.setItalic(False)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 850, 450))
        self.widget.setMinimumSize(QtCore.QSize(850, 450))
        self.widget.setMaximumSize(QtCore.QSize(850, 450))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.background = QtWidgets.QLabel(self.widget)
        self.background.setEnabled(True)
        self.background.setGeometry(QtCore.QRect(0, 0, 850, 350))
        self.background.setMinimumSize(QtCore.QSize(850, 350))
        self.background.setMaximumSize(QtCore.QSize(850, 350))
        self.background.setStyleSheet("background-image: url(image/background2.png);\n"
"border-radius: 20px;\n"
"background-repeat: no-repeat;")
        self.background.setText("")
        self.background.setScaledContents(False)
        self.background.setAlignment(QtCore.Qt.AlignCenter)
        self.background.setObjectName("background")
        self.in_progress = QtWidgets.QLabel(self.widget)
        self.in_progress.setGeometry(QtCore.QRect(125, 90, 600, 141))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro Light")
        font.setPointSize(20)
        self.in_progress.setFont(font)
        self.in_progress.setStyleSheet("color: rgb(255, 255, 255);")
        self.in_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.in_progress.setWordWrap(True)
        self.in_progress.setObjectName("in_progress")
        self.stop_button = QtWidgets.QPushButton(self.widget)
        self.stop_button.setEnabled(True)
        self.stop_button.setGeometry(QtCore.QRect(330, 280, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.stop_button.setFont(font)
        self.stop_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stop_button.setAutoFillBackground(False)
        self.stop_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"\n"
"QPushButton {\n"
"                background-color: white; /* Исходный цвет */\n"
"                border: 1px solid #8f8f91; /* Граница, если нужно */\n"
"            }\n"
"QPushButton:hover {\n"
"                background-color: #dcdcdc; /* Цвет при наведении */\n"
"}")
        self.stop_button.setAutoDefault(False)
        self.stop_button.setObjectName("stop_button")
        self.login_button = QtWidgets.QPushButton(self.widget)
        self.login_button.setEnabled(True)
        self.login_button.setGeometry(QtCore.QRect(330, 280, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login_button.setAutoFillBackground(False)
        self.login_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"\n"
"QPushButton {\n"
"background-color: white; /* Исходный цвет */\n"
"border: 1px solid #8f8f91; /* Граница, если нужно */\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #dcdcdc; /* Цвет при наведении */\n"
"}")
        self.login_button.setAutoDefault(False)
        self.login_button.setObjectName("login_button")
        self.hyus_radio = QtWidgets.QRadioButton(self.widget)
        self.hyus_radio.setGeometry(QtCore.QRect(620, 170, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.hyus_radio.setFont(font)
        self.hyus_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.hyus_radio.setObjectName("hyus_radio")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(365, 10, 120, 60))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/image/123123.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.watchgamestv = QtWidgets.QLabel(self.widget)
        self.watchgamestv.setGeometry(QtCore.QRect(475, 100, 64, 64))
        self.watchgamestv.setStyleSheet("background-image: url(image/4324234.png);\n"
"border-radius: 10px;")
        self.watchgamestv.setText("")
        self.watchgamestv.setObjectName("watchgamestv")
        self.pkle_radio = QtWidgets.QRadioButton(self.widget)
        self.pkle_radio.setGeometry(QtCore.QRect(312, 170, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pkle_radio.setFont(font)
        self.pkle_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.pkle_radio.setObjectName("pkle_radio")
        self.watchgamestv_radio = QtWidgets.QRadioButton(self.widget)
        self.watchgamestv_radio.setGeometry(QtCore.QRect(420, 170, 181, 40))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.watchgamestv_radio.setFont(font)
        self.watchgamestv_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.watchgamestv_radio.setObjectName("watchgamestv_radio")
        self.hyus = QtWidgets.QLabel(self.widget)
        self.hyus.setGeometry(QtCore.QRect(630, 100, 64, 64))
        self.hyus.setStyleSheet("background-image: url(image/6565656.png);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.hyus.setText("")
        self.hyus.setObjectName("hyus")
        self.pkle = QtWidgets.QLabel(self.widget)
        self.pkle.setGeometry(QtCore.QRect(320, 100, 64, 64))
        self.pkle.setStyleSheet("background-image: url(image/55345345.png);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.pkle.setText("")
        self.pkle.setObjectName("pkle")
        self.wrewards = QtWidgets.QLabel(self.widget)
        self.wrewards.setGeometry(QtCore.QRect(165, 100, 64, 64))
        self.wrewards.setStyleSheet("background-image: url(image/64234.png);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.wrewards.setText("")
        self.wrewards.setObjectName("wrewards")
        self.wrewards_radio = QtWidgets.QRadioButton(self.widget)
        self.wrewards_radio.setGeometry(QtCore.QRect(120, 170, 161, 40))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.wrewards_radio.setFont(font)
        self.wrewards_radio.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.wrewards_radio.setObjectName("wrewards_radio")
        self.close_button = QtWidgets.QPushButton(self.widget)
        self.close_button.setGeometry(QtCore.QRect(810, 10, 25, 25))
        self.close_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_button.setMouseTracking(False)
        self.close_button.setStyleSheet("border-image: url(image/lolo.png);")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.description = QtWidgets.QLabel(self.widget)
        self.description.setGeometry(QtCore.QRect(220, 230, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Gotham Pro Medium")
        font.setPointSize(10)
        self.description.setFont(font)
        self.description.setAutoFillBackground(False)
        self.description.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgba(21, 21, 21, 0.5);\n"
"border-radius: 5px;")
        self.description.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.description.setText("Сейчас никто из стримеров не ведёт трансляции.")
        self.description.setTextFormat(QtCore.Qt.AutoText)
        self.description.setScaledContents(False)
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setWordWrap(True)
        self.description.setOpenExternalLinks(False)
        self.description.setObjectName("description")
        self.wrap_button = QtWidgets.QPushButton(self.widget)
        self.wrap_button.setGeometry(QtCore.QRect(760, 10, 25, 25))
        self.wrap_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wrap_button.setMouseTracking(False)
        self.wrap_button.setStyleSheet("border-image: url(image/wrape.png);")
        self.wrap_button.setText("")
        self.wrap_button.setObjectName("wrap_button")
        self.live_hyus = QtWidgets.QLabel(self.widget)
        self.live_hyus.setGeometry(QtCore.QRect(680, 80, 81, 31))
        self.live_hyus.setStyleSheet("background-image: url(image/live.png);\n"
"background-repeat: no-repeat;\n"
"background-size: cover;")
        self.live_hyus.setText("")
        self.live_hyus.setObjectName("live_hyus")
        self.live_watchgamestv = QtWidgets.QLabel(self.widget)
        self.live_watchgamestv.setGeometry(QtCore.QRect(525, 80, 81, 31))
        self.live_watchgamestv.setStyleSheet("background-image: url(image/live.png);\n"
"background-repeat: no-repeat;\n"
"background-size: cover;")
        self.live_watchgamestv.setText("")
        self.live_watchgamestv.setObjectName("live_watchgamestv")
        self.live_pkle = QtWidgets.QLabel(self.widget)
        self.live_pkle.setGeometry(QtCore.QRect(370, 80, 81, 31))
        self.live_pkle.setStyleSheet("background-image: url(image/live.png);\n"
"background-repeat: no-repeat;\n"
"background-size: cover;")
        self.live_pkle.setText("")
        self.live_pkle.setObjectName("live_pkle")
        self.live_wrewards = QtWidgets.QLabel(self.widget)
        self.live_wrewards.setGeometry(QtCore.QRect(215, 80, 81, 31))
        self.live_wrewards.setStyleSheet("background-image: url(image/live.png);\n"
"background-repeat: no-repeat;\n"
"background-size: cover;")
        self.live_wrewards.setText("")
        self.live_wrewards.setObjectName("live_wrewards")
        self.background.raise_()
        self.login_button.raise_()
        self.logo.raise_()
        self.close_button.raise_()
        self.description.raise_()
        self.watchgamestv.raise_()
        self.wrap_button.raise_()
        self.hyus_radio.raise_()
        self.hyus.raise_()
        self.watchgamestv_radio.raise_()
        self.wrewards.raise_()
        self.pkle.raise_()
        self.pkle_radio.raise_()
        self.wrewards_radio.raise_()
        self.live_watchgamestv.raise_()
        self.live_pkle.raise_()
        self.live_hyus.raise_()
        self.live_wrewards.raise_()
        self.in_progress.raise_()
        self.stop_button.raise_()
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WRewardsParser"))
        self.login_button.setText(_translate("MainWindow", "ПАРСИТЬ"))
        self.hyus_radio.setText(_translate("MainWindow", "HYUS"))
        self.pkle_radio.setText(_translate("MainWindow", "PKLE"))
        self.watchgamestv_radio.setText(_translate("MainWindow", "WATCHGAMES"))
        self.wrewards_radio.setText(_translate("MainWindow", "WREWARDS"))
        self.in_progress.setText(_translate("MainWindow", "Парсер запущен и пришлет вам уведомление о розыгрыше когда он начнётся. Отдыхайте!"))
        self.stop_button.setText(_translate("MainWindow", "Остановить"))
